### ISSUE TITLE
Extra option to have fixed columns for termfair layouts

### ISSUE THREAD

**Issue by Euren** [lcpz/lain#333]
I opened this as a general awesome feature request at https://github.com/awesomeWM/awesome/issues/1661 but it might be more about the mentioned layouts layout.

I would like to get the following behavior:

```
   +---+---+---+      +-+---+---+-+      +---+---+---+      +---+---+---+    
   |           |      |     |     |      |   |   |   |      |   |   | 3 | 
   |     1     |  ->  |  1  |  2  | ->   | 1 | 2 | 3 |  ->  + 1 + 2 +---+ 
   |           |      |     |     |      |   |   |   |      |   |   | 4 |      
   +---+---+---+      +-+---+---+-+      +---+---+---+      +---+---+---+     
               
```

Two masters with all other new windows filling in the third column. Currently `termfair` will split all except the first column.

**Comment by Maxlufs** [comment]
Bumping this one, this gets more and more commonly used given popularity of ultra wide monitors.

**Comment by copycat-killer** [comment]
@Maxlufs Please don't spam posts. I'm still very busy at the moment, but I hope I'll do this for the next Awesome release.

**Comment by lcpz** [comment]
I finally gave it a look.

Summarising, what you want is to make `awful.layout.suit.tile` arrange master windows in columns rather than rows. 

Unfortunately `termfair` arranges windows in a grid-like layout, which is completely different from default `tile`: the fact that after the 4th arrangement it gets similar to your wish is fortuitous.

The only thing to do is to work on https://github.com/awesomeWM/awesome/issues/1661. We already can define the number of master windows with `beautiful.master_count`, maybe we could introduce a variable like `beautiful.master_orientation` that any static layout could respect. 

I do not know how much is worth it, considering that [it will be superseded](https://github.com/awesomeWM/awesome/pull/644), but I will see if I can contribute.
