### ISSUE TITLE
alsabar-pulsebar naughty notification with xresources.apply_dpi

### ISSUE THREAD

**Issue by sprnza** [lcpz/lain#394]
Hi there!
I've got my wibar vertical with width set to 54 and I don't understand why the number of ticks that are being displayed in notification is based on wibar width? See alsabar.lua#120. In my case notification gets a line break with this amount of ticks displayed.

**Comment by lcpz** [comment]
> Why the number of ticks that are being displayed in notification is based on wibar width?

Because the notification is based on the widget dimensions, which in turn are based on the wibox they are placed in.

> In my case notification gets a line break with this amount of ticks displayed.

Please give me your full `alsabar` configuration and a screenshot of the issue.

**Comment by lcpz** [comment]
Default number of maximum ticks is 20, like the height of a default horizontal wibar. If possible, this number is replaced with `wibar.height` if you're using a horizontal wibar, or `wibar.width` if you're using a vertical wibar (like in your case). This allows to make the notification proportional to your desktop dimensions.

Removing `notification_preset.width` since it's automatically calculated, I get this:

![20180606125255](https://user-images.githubusercontent.com/1777696/41034138-feccde42-6988-11e8-8b71-c12406deaf34.png)

(I'm using `pulsebar` because I have PulseAudio, but the notification code is the same.)

Check if it still happens after disabling `xresources.apply_dpi`.

**Comment by sprnza** [comment]
I've already removed `notification_preset.width` not sure why I was taking screenshot with the setting added, sorry. It doesn't happen if I disable `xresources.apply_dpi`.

**Comment by lcpz** [comment]
> It doesn't happen if I disable `xresources.apply_dpi`.

Good. We just have to find a way to disable it for `naughty`.

@Elv13 Is it possible?

**Comment by lcpz** [comment]
@sprnza Does this happen with other notifications too?

**Comment by sprnza** [comment]
I don't have the ticks used with other notifications.

**Comment by lcpz** [comment]
I meant in general, so I assume it's a no.

**Comment by sprnza** [comment]
Nope, sorry I hadn't got your question.

**Comment by lcpz** [comment]
OK, so we know the why, and it's not related to this repo.

The DPI setting is most likely global and there's nothing I can do on my side to help you.
