### ISSUE TITLE
Change default width of layout termfair.center

### ISSUE THREAD

**Issue by dummys** [lcpz/lain#422]
Hi, I'm looking how to change the default width of the layout termfair.center. How the default width is calculated ? Is it possible to add an option to modify it please ?
Thanks

**Comment by dummys** [comment]
no idea ?

**Comment by lcpz** [comment]
Hi, I can't help at the moment as I am super busy, but I will get at it
ASAP. In the meantime, try to ask the [community](
https://awesomewm.org/community/).

Il giorno gio 14 mar 2019 alle ore 12:43 dummys <notifications@github.com>
ha scritto:

**Comment by dummys** [comment]
ok no problem, thanks

**Comment by lcpz** [comment]
@dummys The width of each column is defined by the `nmaster` variable. Read [here](https://github.com/lcpz/lain/wiki/Layouts#termfaircenter).

More precisely, the calculation is `your_monitor_width / nmaster`, so that each column has the same width. That is, if you set in your `rc.lua`:

```lua
lain.layout.termfair.center.nmaster = 2
```

Then, when you have only 1 client, this will have half of your screen width if `n <= 2`, and `1/n` otherwise.

Currently, you can not resize the width of clients with this layout, because it misses a `mouse_resize_handler`. Another user [added one for centerwork](https://github.com/lcpz/lain/issues/395). If you want, you can see that work and try to come up with a handler for this layout, then do a `git pull` request. Otherwise, I can look into it, even though I do not find it [durable](https://github.com/lcpz/lain/issues/395#issuecomment-406233265).

**Comment by kresbeatz** [comment]
It will be great if it function like XMonad Three Columns layout (with resizing). However to me it looks like mix of centerfair and ThreeColMid in XMonad. So if you have one window it occupies whole space, if two - it splits vertical in center (same as tile layout) and if there are three window master is in center and when you resize it via default keybindings center (master) window shrinks/expands respectively. Navigating between windows is the same as in tile layout (basically in the first window is master, which is moves to the center if there is 3 or more windows and every other window is stack). If there is more than 3 windows it start divide horizontally left and right windows (something like centerwork). It's very convenient on UltraWide 34" monitor. 
--
Or it will be awesome if I can use different set of navigation keybindings depending on layout, so I Mod+h/j/k/l in centerwork for awful.client.focus.bydirection and if the current layout is not centerwork then Mod+h/j/k/l will do awful.tag.incmwfact and awful.client.focus.byidx respectively. I know how to achieve this in Haskell, but not in LUA, unfortunately :(
