### ISSUE TITLE
setup github action to automatically publish to luarocks

### ISSUE THREAD

**Issue by airtonix** [lcpz/lain#542]
https://luarocks.org/search?q=lain

There's one there, but it's ancient.

Yours is obviously the offical one, so it should be up on Luarocks.

**Comment by Aire-One** [comment]
Hello,

The wiki (https://github.com/lcpz/lain/wiki) recommends installing lain from Luarocks with the command

```
luarocks install lcpz/lain
```

This command will target the version from https://luarocks.org/modules/lcpz/lain.

Installing a rock from SCM should not require updates (as long as the rockspec doesn't change) since you are actually downloading the files from this repository.

I, however, completely second this request. The lain-scm-1.rockspec file from Luarocks is not in sync with the one from the repository, and it would be good to also have tagged releases on Luarocks.

**Comment by lcpz** [comment]
@airtonix Do you mean to automatically *upload* to LuaRocks every time the `rockspec` changes?

If so, that needs to expose my API key, which clearly is not safe.

For the time being, I uploaded a new `scm-2` version, following #547.

**Comment by Aire-One** [comment]
> https://luarocks.org/search?q=lain
> There's one there, but it's ancient.

@lcpz, I think the complaint here is that your package (`lcpz/lain`) is not in the root manifest. So a basic search only yields the old package from @aajjbb.

> If so, that needs to expose my API key, which clearly is not safe.

GitHub Actions has a "secret" feature to manage your API key without exposing it.

https://docs.github.com/en/actions/security-guides/encrypted-secrets

> For the time being, I uploaded a new scm-2 version, following https://github.com/lcpz/lain/pull/547.

That's a great news! :tada:

**Comment by lcpz** [comment]
> GitHub Actions has a "secret" feature to manage your API key without exposing it.

Thanks for letting me know.

@aajjbb Hi old friend, could you please remove your rock?

**Comment by aajjbb** [comment]
Hey there; the original rock is now gone. I'm glad this can now be automatized :)

**Comment by lcpz** [comment]
> Hey there; the original rock is now gone. I'm glad this can now be automatized :)

Thank you, added Action and uploaded `rockspec` to [root manifest](https://luarocks.org/modules/lcpz/lain).
